name: Firework
favicon: null
layout_spectrum: 0.14552
typography_spectrum: 0.34755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e86826'
    - '#56595b'
    - '#fad9c9'
    - '#b3b8b8'
    - '#ffffff'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
